spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice3
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9100
